-- AlterTable
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "discountType" TEXT NOT NULL DEFAULT 'PERCENTAGE';
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "minOrderAmount" DOUBLE PRECISION;
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "maxDiscount" DOUBLE PRECISION;
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "usageLimit" INTEGER;
ALTER TABLE "offers" ADD COLUMN IF NOT EXISTS "usedCount" INTEGER NOT NULL DEFAULT 0;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "offers_code_key" ON "offers"("code");
CREATE INDEX IF NOT EXISTS "offers_code_idx" ON "offers"("code");
